/*
  Warnings:

  - The values [PENDING_LOAN_OFFICER_REVIEW] on the enum `LoanStatus` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "LoanStatus_new" AS ENUM ('DRAFT', 'PENDING_INSPECTOR_ASSIGNMENT', 'PENDING_VERIFICATION', 'VERIFICATION_IN_PROGRESS', 'VERIFICATION_COMPLETED', 'VERIFICATION_FAILED', 'PENDING_LOAN_OFFICER_ASSIGNMENT', 'PENDING_LOAN_OFFICER_APPLICATION_REVIEW', 'PENDING_LOAN_OFFICER_VERIFICATION_REVIEW', 'PENDING_LOAN_OFFICER_SANCTION_NOTE', 'PENDING_CEO_APPLICATION_REVIEW', 'PENDING_CEO_SANCTION_NOTE', 'PENDING', 'APPROVED', 'REJECTED', 'REJECTED_BY_APPLICANT', 'UNDER_REVIEW');
ALTER TABLE "LoanApplication" ALTER COLUMN "status" TYPE "LoanStatus_new" USING ("status"::text::"LoanStatus_new");
ALTER TYPE "LoanStatus" RENAME TO "LoanStatus_old";
ALTER TYPE "LoanStatus_new" RENAME TO "LoanStatus";
DROP TYPE "LoanStatus_old";
COMMIT;
