-- CreateEnum
CREATE TYPE "BankOnboardingStatus" AS ENUM ('BANK_CREATED', 'BANK_ONBOARDED', 'ADMIN_CREATED', 'SUBSCRIPTION_CREATED', 'USERS_CREATED', 'CONFIGURATIONS_CREATED');

-- AlterTable
ALTER TABLE "Bank" ADD COLUMN     "onboardingStatus" "BankOnboardingStatus" NOT NULL DEFAULT 'BANK_CREATED';
