/*
  Warnings:

  - The values [APPLICATION_REVIEWED,VERIFICATION_REVIEWED,VERIFICATION_REJECTED] on the enum `TimelineEventType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "TimelineEventType_new" AS ENUM ('APPLICATION_CREATED', 'APPLICATION_UPDATED', 'APPLICATION_DELETED', 'APPLICATION_REOPENED', 'APPLICATION_APPROVED', 'APPLICATION_REJECTED', 'APPLICATION_REVIEW_REJECTED', 'APPLICATION_REVIEW_APPROVED', 'STATUS_CHANGE', 'DOCUMENT_UPLOADED', 'DOCUMENT_REVIEWED', 'DOCUMENT_DELETED', 'DOCUMENT_REQUESTED', 'USER_CREATED', 'USER_ASSIGNED_ROLE', 'USER_REMOVED_ROLE', 'VERIFICATION_STARTED', 'VERIFICATION_COMPLETED', 'VERIFICATION_FAILED', 'VERIFICATION_REVIEW_APPROVED', 'VERIFICATION_REVIEW_REJECTED', 'VERIFICATION_REMARK_ADDED', 'ACTION_REQUESTED', 'ACTION_APPROVED', 'ACTION_REJECTED', 'ACTION_CANCELLED', 'ACTION_REVIEWED', 'NOTE_ADDED', 'REMARK_ADDED', 'SANCTION_REMARK_ADDED', 'SYSTEM_EVENT', 'AUTO_VERIFICATION', 'SCHEDULED_TASK_COMPLETED', 'ACCESS_GRANTED', 'ACCESS_REVOKED');
ALTER TABLE "TimelineEvent" ALTER COLUMN "timelineEventType" TYPE "TimelineEventType_new" USING ("timelineEventType"::text::"TimelineEventType_new");
ALTER TYPE "TimelineEventType" RENAME TO "TimelineEventType_old";
ALTER TYPE "TimelineEventType_new" RENAME TO "TimelineEventType";
DROP TYPE "TimelineEventType_old";
COMMIT;
